baseURL = "https://hellenic-streets.ctl.columbia.edu/"
copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Hellenic Streets"
cloudfrontBase = "https://d2b5j58ir6uajk.cloudfront.net"

[taxonomies]
  # default taxonomies
  category = 'categories'
  tag = 'tags'

  # custom taxonomies
  street = 'streets'
  neighborhood = 'neighborhoods'